# Generated by Django 4.0.3 on 2023-07-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='프로필 사진'),
        ),
    ]
